const $ = id => document.getElementById(id);
const video=$('camera'), canvas=$('reticle'), ctx=canvas.getContext('2d');
let socket, active=false, calibrated=false, yaw0=null, lastAlpha=null, yaw=0, target=null, landmarker=null, detecting=false, screenJoints=[];
const pose={x:0,y:0,z:0};
const wsURL=`${location.protocol==='https:'?'wss':'ws'}://${location.host}/ws/observer`;
const JOINTS=[['nose',0],['left_shoulder',11],['right_shoulder',12],['left_hip',23],['right_hip',24],['left_ankle',27],['right_ankle',28]];
const LINKS=[['nose','left_shoulder'],['nose','right_shoulder'],['left_shoulder','right_shoulder'],['left_shoulder','left_hip'],['right_shoulder','right_hip'],['left_hip','right_hip'],['left_hip','left_ankle'],['right_hip','right_ankle']];
function send(x){if(socket?.readyState===WebSocket.OPEN)socket.send(JSON.stringify(x))}
function posePacket(){return {position:[pose.x,pose.y,pose.z],quaternionXyzw:[0,Math.sin(yaw/2),0,Math.cos(yaw/2)],timestampNs:Date.now()*1e6}}
function render(){ctx.clearRect(0,0,canvas.width,canvas.height);const mapped=Object.fromEntries(screenJoints.map(j=>[j.name,j]));ctx.strokeStyle='#bafa59';ctx.lineWidth=3;LINKS.forEach(([a,b])=>{if(mapped[a]&&mapped[b]){ctx.beginPath();ctx.moveTo(mapped[a].x*canvas.width,mapped[a].y*canvas.height);ctx.lineTo(mapped[b].x*canvas.width,mapped[b].y*canvas.height);ctx.stroke()}});if(!target)return;const x=target.x*canvas.width,y=target.y*canvas.height;ctx.beginPath();ctx.arc(x,y,26,0,Math.PI*2);ctx.stroke();ctx.font='11px DM Mono';ctx.fillStyle='#bafa59';ctx.fillText(`${$('range').value}m`,x+35,y)}
function updatePose(){const p=posePacket();$('position').textContent=[p.position[0],p.position[1],p.position[2]].map(n=>`${n>=0?'+':'−'}${Math.abs(n).toFixed(2)}`).join(' · ');$('orientation').textContent=`${(yaw*180/Math.PI).toFixed(0)}° yaw`;if(calibrated)send({type:'pose',sequence:Date.now(),localPose:p});if(target&&calibrated)sendDetection()}
function toPhonePoint(x,y,d){const fov=Math.PI/3;return [(x-.5)*2*d*Math.tan(fov/2),-(y-.5)*2*d*Math.tan(fov/2),-d]}
function sendDetection(){const d=Number($('range').value), point=toPhonePoint(target.x,target.y,d);const jointsPhone=screenJoints.map(j=>({name:j.name,position:toPhonePoint(j.x,j.y,d),confidence:j.confidence}));send({type:'detection',sequence:Date.now(),subjectId:detecting?'person_01':'manual_target',timestampNs:Date.now()*1e6,positionPhone:point,jointsPhone,confidence:detecting?.8:.6})}
async function startCamera(){try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});video.srcObject=stream;await video.play();$('cameraPrompt').style.display='none';$('motionButton').disabled=false;$('calibrateButton').disabled=false;$('detectButton').disabled=false;$('cameraButton').disabled=true;canvas.width=video.videoWidth;canvas.height=video.videoHeight;active=true}catch(e){$('cameraPrompt').innerHTML=`<b>Camera unavailable</b><span>${location.protocol==='https:'?'Allow camera permission and retry.':'Phone camera requires an HTTPS page. See the laptop instructions.'}</span>`}}
async function enableDetection(){try{$('detectButton').disabled=true;$('detectButton').textContent='Loading pose model…';const vision=await import('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest');const files=await vision.FilesetResolver.forVisionTasks('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest/wasm');landmarker=await vision.PoseLandmarker.createFromOptions(files,{baseOptions:{modelAssetPath:'https://storage.googleapis.com/mediapipe-models/pose_landmarker/pose_landmarker_lite/float16/latest/pose_landmarker_lite.task'},runningMode:'VIDEO',numPoses:1,minPoseDetectionConfidence:.5,minTrackingConfidence:.5});detecting=true;$('detectButton').textContent='Person detection active';detectLoop()}catch(e){$('detectButton').disabled=false;$('detectButton').textContent='Detection unavailable — tap target';console.error(e)}}
function detectLoop(){if(!detecting||!landmarker)return;const result=landmarker.detectForVideo(video,performance.now());const points=result.landmarks?.[0];if(points){screenJoints=JOINTS.map(([name,index])=>({name,x:points[index].x,y:points[index].y,confidence:points[index].visibility??.8})).filter(j=>j.confidence>.35);const a=points[23],b=points[24];target={x:(a.x+b.x)/2,y:(a.y+b.y)/2};render();if(calibrated)sendDetection()}else{screenJoints=[];render()}setTimeout(detectLoop,100)}
async function enableMotion(){try{if(typeof DeviceOrientationEvent !== 'undefined' && typeof DeviceOrientationEvent.requestPermission==='function'){const p=await DeviceOrientationEvent.requestPermission();if(p!=='granted')throw Error('Permission denied')}window.addEventListener('deviceorientation',e=>{if(e.alpha==null)return;lastAlpha=e.alpha;if(yaw0===null)yaw0=lastAlpha;yaw=(lastAlpha-yaw0)*Math.PI/180;updatePose()});$('motionButton').textContent='Motion enabled';$('motionButton').disabled=true}catch{$('motionButton').textContent='Motion permission denied'}}
function calibrate(){if(!active)return;pose.x=0;pose.y=0;pose.z=0;if(lastAlpha!==null)yaw0=lastAlpha;yaw=0;calibrated=true;send({type:'calibration',localPose:posePacket()});$('calibrateButton').textContent='Phone calibrated';$('calibrateButton').disabled=true;updatePose()}
function connect(){socket=new WebSocket(wsURL);socket.onopen=()=>{$('hub').textContent='HUB CONNECTED'};socket.onclose=()=>{ $('hub').textContent='RECONNECTING';setTimeout(connect,2000)}}
$('cameraButton').onclick=startCamera;$('detectButton').onclick=enableDetection;$('motionButton').onclick=enableMotion;$('calibrateButton').onclick=calibrate;$('range').oninput=()=>{$('rangeOutput').textContent=`${Number($('range').value).toFixed(1)} m`;if(target)sendDetection()};canvas.onclick=e=>{const r=canvas.getBoundingClientRect();target={x:(e.clientX-r.left)/r.width,y:(e.clientY-r.top)/r.height};screenJoints=[];render();sendDetection()};document.querySelectorAll('[data-axis]').forEach(b=>b.onclick=()=>{pose[b.dataset.axis]+=Number(b.dataset.step);updatePose()});$('resetPosition').onclick=()=>{pose.x=pose.y=pose.z=0;updatePose()};connect();setInterval(updatePose,100);
