const $ = id => document.getElementById(id);
const video = $('video'), canvas = $('overlay'), ctx = canvas.getContext('2d');
let intrinsics = null, target = null, calibrated = false, stream = null;
const socketURL = `${location.protocol === 'https:' ? 'wss' : 'ws'}://${location.host}/ws/viewer`;

function text(el, value) { $(el).textContent = value; }
function triplet(a) { return a.map(v => `${v >= 0 ? '+' : '−'}${Math.abs(v).toFixed(2)}`).join(' · '); }
async function refreshIntrinsics() { const result = await fetch('/camera/intrinsics').then(r => r.json()); intrinsics = result.intrinsics; text('intrinsics', intrinsics ? `${intrinsics.fx.toFixed(0)}px / ${intrinsics.width}×${intrinsics.height}` : 'Not calibrated'); }
async function startCamera() { try { stream = await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:1280},height:{ideal:720}},audio:false}); video.srcObject=stream; await video.play(); $('empty').style.display='none'; $('calibrate').disabled=false; $('startCamera').textContent='Camera running'; $('startCamera').disabled=true; resize(); if(!intrinsics){intrinsics={width:video.videoWidth,height:video.videoHeight,fx:video.videoWidth*.9,fy:video.videoWidth*.9,cx:video.videoWidth/2,cy:video.videoHeight/2};text('intrinsics','Estimated 60° FOV');} } catch { text('calibrationStatus','Camera permission was denied'); } }
function resize() { canvas.width=video.videoWidth||1280; canvas.height=video.videoHeight||720; }
function send(message) { if (window.relay?.readyState === WebSocket.OPEN) window.relay.send(JSON.stringify(message)); }
function calibrate() { calibrated=true; send({type:'calibration',localPose:{position:[0,0,0],quaternionXyzw:[0,0,0,1],timestampNs:Date.now()*1e6}}); text('calibrationStatus','Laptop world origin fixed'); $('calibrate').textContent='Laptop calibrated'; $('calibrate').disabled=true; }
function project(canonical){const cv=[canonical[0],-canonical[1],-canonical[2]];if(cv[2]<=.08)return null;const sx=canvas.width/intrinsics.width,sy=canvas.height/intrinsics.height;return {x:(intrinsics.fx*cv[0]/cv[2]+intrinsics.cx)*sx,y:(intrinsics.fy*cv[1]/cv[2]+intrinsics.cy)*sy,z:cv[2]}}
function draw() { requestAnimationFrame(draw); ctx.clearRect(0,0,canvas.width,canvas.height); if (!target || !intrinsics || !calibrated) return; const p=project(target.positionLaptop); if(!p){text('targetReadout',`TARGET OUTSIDE LAPTOP VIEW · no overlay`);return;} const visible=p.x>=0&&p.x<=canvas.width&&p.y>=0&&p.y<=canvas.height;text('targetReadout',visible?`REMOTE TARGET · ${p.z.toFixed(1)}m`:`TARGET OUTSIDE LAPTOP FOV · no overlay`);if(!visible)return;const joints=Object.fromEntries((target.joints||[]).map(j=>[j.name,project(j.positionLaptop)]).filter(([,v])=>v));const links=[['nose','left_shoulder'],['nose','right_shoulder'],['left_shoulder','right_shoulder'],['left_shoulder','left_hip'],['right_shoulder','right_hip'],['left_hip','right_hip'],['left_hip','left_ankle'],['right_hip','right_ankle']];ctx.strokeStyle='#bbfa5c';ctx.shadowColor='#bbfa5c';ctx.shadowBlur=10;ctx.lineWidth=4;links.forEach(([a,b])=>{if(joints[a]&&joints[b]){ctx.beginPath();ctx.moveTo(joints[a].x,joints[a].y);ctx.lineTo(joints[b].x,joints[b].y);ctx.stroke()}});ctx.shadowBlur=0;ctx.fillStyle='rgba(187,250,92,.18)';ctx.beginPath();ctx.arc(p.x,p.y,34,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.font='13px DM Mono';ctx.fillStyle='#bbfa5c';ctx.fillText(`${target.subjectId||'PERSON_01'} · ${p.z.toFixed(1)}m`,p.x+45,p.y); }
function connect(){window.relay=new WebSocket(socketURL); relay.onopen=()=>{text('connection','HUB CONNECTED');$('connection').classList.add('live');if(calibrated)calibrate()};relay.onmessage=e=>{const p=JSON.parse(e.data);if(p.type==='debug_pose'){text('phonePose',triplet(p.phoneWorld.position));}if(p.type==='target'){target=p;text('targetPose',triplet(p.positionLaptop));}};relay.onclose=()=>{text('connection','HUB RECONNECTING');$('connection').classList.remove('live');setTimeout(connect,2000)}}
$('startCamera').onclick=startCamera;$('calibrate').onclick=calibrate;video.onloadedmetadata=resize;refreshIntrinsics();connect();draw();
